import {
  ImageIcon, Home, PackageCheck, Ruler, Sparkles,
  Wrench, PawPrint, ShieldCheck, Scale,
} from 'lucide-react'

// Guia oficial de imagens pra produtos (Manual de Marketplace da CoisaPet,
// enviado pelo Raphael em 15/09) — vale pro site E pra exportação/migração
// futura de fotos pro Mercado Livre e Shopee, não é só documentação
// interna. Ver coisapet.md.
export const CATEGORIES = {
  comercial:   { label: 'Comercial',   short: 'C',  tone: 'bg-sky-100 text-sky-700' },
  emocional:   { label: 'Emocional',   short: 'E',  tone: 'bg-rose-100 text-rose-700' },
  educacional: { label: 'Educacional', short: 'ED', tone: 'bg-amber-100 text-amber-700' },
  opcional:    { label: 'Opcional',    short: 'OP', tone: 'bg-slate-100 text-slate-600' },
}

export const MEDIA_CHECKLIST = [
  {
    slot: 1,
    category: 'comercial',
    title: 'Produto / Hero',
    description: 'Produto completo e montado em perspectiva 3/4, sobre fundo branco puro. Iluminação de estúdio, sombra leve e o produto ocupando boa parte da composição.',
    tags: ['Fundo branco', 'Perspectiva 3/4', 'Produto completo', 'Sem descrição', 'Sem pet'],
    objective: 'Identificação imediata do produto',
    quote: 'É isso que estou comprando?',
    warning: 'Não adicionar acessórios que ainda não correspondam ao produto.',
    icon: ImageIcon,
  },
  {
    slot: 2,
    category: 'emocional',
    title: 'Ambientada + Pet',
    description: 'Produto inserido em um ambiente residencial realista, bonito e acolhedor. Mostrar o produto montado e organizado, acompanhado exclusivamente por uma espécie compatível.',
    tags: ['Ambiente residencial', 'Pet compatível', 'Luz natural', 'Escala real', 'Lifestyle'],
    objective: 'Gerar desejo e contextualizar escala',
    quote: 'Como isso fica na minha casa?',
    warning: 'Evitar cenários excessivamente perfeitos ou artificiais — a imagem precisa parecer possível na rotina do comprador.',
    icon: Home,
  },
  {
    slot: 3,
    category: 'comercial',
    title: 'O que acompanha',
    description: 'Mostrar visualmente todos os itens que acompanham aquele SKU, organizados como um kit. Cada componente pode receber uma identificação curta.',
    tags: ['Produto', 'Acessórios inclusos', 'Nomes curtos', 'Composição organizada'],
    objective: 'Deixar claro tudo o que o cliente recebe',
    quote: 'Isso vem junto?',
    warning: 'Nunca mostrar itens que não acompanham essa variação específica do produto.',
    icon: PackageCheck,
    hint: p => p.accessories_included || (p.includes_wheel ? `Inclui rodinha${p.wheel_diameter_cm ? ` (${p.wheel_diameter_cm}cm)` : ''}` : null),
  },
  {
    slot: 4,
    category: 'comercial',
    title: 'Dimensões',
    description: 'Produto isolado com linhas técnicas indicando largura, profundidade e altura. Layout extremamente limpo, sem parágrafos ou excesso de informação.',
    tags: ['Largura', 'Profundidade', 'Altura', 'Escala certa'],
    objective: 'Facilitar a percepção do tamanho real',
    quote: 'Cabe onde eu quero colocar?',
    icon: Ruler,
    hint: p => (p.width_cm && p.height_cm && p.depth_cm) ? `${p.width_cm} × ${p.height_cm} × ${p.depth_cm} cm` : null,
  },
  {
    slot: 5,
    category: 'educacional',
    title: 'Principais benefícios',
    description: 'Headline curta acompanhada de no máximo três ou quatro diferenciais reais do produto. A comunicação deve transformar características em benefícios reais pro pet e pro tutor.',
    tags: ['3-4 benefícios', 'Headline curta', 'Pouco texto', 'Argumentos reais'],
    objective: 'Explicar rapidamente por que escolher o produto',
    quote: 'Por que esse produto é melhor?',
    warning: 'Evitar excesso de ícones, floreios e poluição visual.',
    icon: Sparkles,
  },
  {
    slot: 6,
    category: 'educacional',
    title: 'Detalhes construtivos',
    description: 'Fotografias macro ou closes mostrando materiais, encaixes, acabamento, MDF/laminado, ventilação e outros detalhes importantes daquele produto.',
    tags: ['Material', 'Acabamento', 'Encaixe', 'Ventilação', 'Construção'],
    objective: 'Transmitir qualidade e justificar valor',
    quote: 'Isso é bem feito?',
    icon: Wrench,
  },
  {
    slot: 7,
    category: 'emocional',
    title: 'Uso / Enriquecimento',
    description: 'Mostrar o animal efetivamente utilizando o produto: entrando na toca, comendo na roda, explorando túneis, ou usando o substrato do jeito pretendido.',
    tags: ['Comportamento natural', 'Pet utilizando', 'Proporção coerente', 'Função visível'],
    objective: 'Demonstrar o produto funcionando na prática',
    quote: 'Meu pet vai aproveitar isso?',
    warning: 'Diferente da imagem 02 (lifestyle) — aqui precisa mostrar a função real do produto em uso.',
    icon: PawPrint,
  },
  {
    slot: 8,
    category: 'educacional',
    title: 'Compatibilidade / Orientação',
    description: 'Informar claramente para quais animais o produto é indicado e, quando necessário, quais espécies não podem utilizá-lo.',
    tags: ['Indicado para', 'Não indicado para', 'Compra consciente', 'Bem-estar'],
    objective: 'Evitar compras inadequadas e reforçar autoridade',
    quote: 'Serve para o meu bichinho?',
    warning: 'Nunca colocar um animal num produto inadequado só pra gerar uma imagem bonita.',
    icon: ShieldCheck,
    hint: p => p.compatible_species?.length ? p.compatible_species.join(', ') : null,
  },
  {
    slot: 9,
    category: 'opcional',
    title: 'Comparativo / Educação',
    description: 'Imagem dedicada a explicar uma escolha de habitat, comportamento natural do pet ou benefício que exija um pouco mais de educação do consumidor.',
    tags: ['Comparação visual', 'Habitat', 'Bem-estar', 'Educação'],
    objective: 'Educar e posicionar a Coisa Pet',
    quote: 'Qual é a escolha mais adequada?',
    warning: 'O foco não deve ser atacar concorrentes, e sim explicar por que essa solução é adequada ao animal.',
    icon: Scale,
  },
]
